
WORKOUT_DURATION_PROMPT = """
    How many weeks long is the workout program?
    """.strip()

EXERCISE_DB_PATH = "exercises_web.json"
exercise_dict = {
    "squat back": "full squat",
    "back squat": "full squat",
    "seated face pull": "cable seated face pull",
    "meadows row": "landmine one arm bent over row",
    "barbell or ez bar curl": "barbell curl",
    "pin squat": "barbell anderson squat",
    "cable reverse flye": "cable one arm reverse fly",
    "block pull": "barbell deadlift from blocks",
    "pause db incline press": "dumbbell incline bench press",
    "db incline press": "dumbbell incline bench press",
    "dumbbell incline press": "dumbbell incline bench press",
    "leg curl": "lever lying leg curl",
    "leg curl choice": "lever lying leg curl",
    "chest supported row": "incline row",
    "overhead tricep extension": "cable overhead triceps extension",
    "single arm overhead tricep extension": "cable alternate triceps extension",
    "cable tricep kickback": "cable kickback",
    "plate shrug": "shrug",
    "neck flexion extension": "lying neck flexion",
    "unilateral leg press": "lever horizontal one leg press",
    "single leg press": "lever horizontal one leg press",
    "long lever plank": "front plank",
    "dip": "chest dip",
    "eccentric accentuated barbell skull crusher": "barbell lying tricep extension skull",
    "constant tension cable triceps kickback": "cable kickback",
    "constant tension cable kneeling pullover": "cable lying extension pullover",
    "prisoner back extension": "45 degree hyperextension",
    "ez bar pronated curl": "ez barbell curl",
    "eccentric accentuated ez bar or barbell curl": "ez barbell curl",
    "ez bar supinated curl": "ez barbell curl",
    "reverse pec deck": "lever seated reverse fly",
    "wall slide": "scapular slide back to wall",
    "sliding leg curl": "leg curl sliding leg curl on floor with towel",
    "leg press": "sled 45 leg press",
    "barbell rdl": "barbell romanian deadlift",
    "db rdl": "dumbbell romanian deadlift",
    "rdl": "romanian deadlift",
    "nordic ham curl": "nordic hamstring curl",
    "hip abduction": "lever seated hip abduction",
    "hip adduction": "lever seated hip adduction",
    "larsen press": "barbell larsen press",
    "db larsen press": "dumbbell larsen press",
    "dumbbell larsen press": "dumbbell larsen press",
    "single arm pulldown": "cable one arm lat pulldown",
    "bayesian curl": "cable one arm bicep curl",
    "unilateral leg curl": "lever seated one leg curl",
    "single leg curl": "lever seated one leg curl",
    "machine strict form row": "seated row",
    "eccentric-accentuated leg extension": "lever seated leg extension",
    "omni grip lat pulldown": "cable bar lateral pulldown",
    "Reverse pec deck protracted scapulae": "lever seated reverse fly",
    "reverse pec deck actively go through a protraction retraction rom": "lever seated reverse fly",
    "l sit hold": "l sit",
    "cable pull through": "cable pull through", 
    "leg extension": "lever seated leg extension",
    "eccentric accentuated pull up": "pull up",
    "optional exercise": "blank",
}

EXERCISE_DB_PATH = "exercises_web.json"
